version: "3.7"
services:
  hibiscus-service:
    image: hibiscus:latest
    container_name: hibiscus
    restart: always
    build: .
    volumes:
      - ./secrets/pwd:/run/secret/pwd
      - ./secrets/HBCIDBService.properties:/hibiscus-server/cfg/de.willuhn.jameica.hbci.rmi.HBCIDBService.properties