version: "3"
services:
  hibiscus-service:
    image: hibiscus:latest
    container_name: hibiscus
    restart: always
    build: .
    volumes:
      - /home/pi/secrets/pwd:/run/secret/pwd
      - /home/pi/secrets/HBCIDBService.properties:/hibiscus-server/cfg/de.willuhn.jameica.hbci.rmi.HBCIDBService.properties
      - /home/pi/.jameica:/.jameica
    ports:
      - 8888:8888
    network_mode: bridge
